### ISSUE TITLE
run train.sh fail

### ISSUE THREAD

**Issue by hawkyy** [Pivotal-Open-Source-Hub/StockInference-Spark#4]
the log:

15/12/29 14:25:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/12/29 14:25:52 WARN Utils: Your hostname, localhost.localdomain resolves to a loopback address: 127.0.0.1; using 172.26.120.12 instead (on interface eth0)
15/12/29 14:25:52 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
15/12/29 14:25:53 WARN MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
## [info 2015/12/29 14:25:56.413 CST <main> tid=0x1] 

  Copyright (C) 1997-2015 Pivotal Software, Inc. All rights reserved. This
  product is protected by U.S. and international copyright and intellectual
  property laws. Pivotal products are covered by one or more patents listed
  at http://www.pivotal.io/patents.  Pivotal is a registered trademark
  of trademark of Pivotal Software, Inc. in the United States and/or other
  jurisdictions.  All other marks and names mentioned herein may be
  trademarks of their respective companies.

---

Java version:   1.0.0-incubating-SNAPSHOT yy 122815 2015-12-28 19:30:20 +0800 javac 1.8.0_60
Native version: native code unavailable
Source revision: 1366ff2d4fcbf54bfad684e9ba9822db2a2b0ff5
Source repository: master
Running on: /172.16.88.1, 8 cpu(s), amd64 Linux 3.10.0-327.3.1.el7.x86_64
Process ID: 14136
User: yy
Current dir: /home/yy/StockInference-Spark/streaming
Home dir: /home/yy
Command Line Parameters:
  -Xms1G
  -Xmx1G
Class Path:
  /opt/spark-1.5.2-bin-hadoop2.6/conf/
  /opt/spark-1.5.2-bin-hadoop2.6/lib/spark-assembly-1.5.2-hadoop2.6.0.jar
  /opt/spark-1.5.2-bin-hadoop2.6/lib/datanucleus-core-3.2.10.jar
  /opt/spark-1.5.2-bin-hadoop2.6/lib/datanucleus-api-jdo-3.2.6.jar
  /opt/spark-1.5.2-bin-hadoop2.6/lib/datanucleus-rdbms-3.2.9.jar
Library Path:
  /usr/java/packages/lib/amd64
  /usr/lib64
  /lib64
  /lib
  /usr/lib
System Properties:
    SPARK_SUBMIT = true
    awt.toolkit = sun.awt.X11.XToolkit
    file.encoding = UTF-8
    file.encoding.pkg = sun.io
    file.separator = /
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.version = 52.0
    java.endorsed.dirs = /opt/jdk1.8.0_60/jre/lib/endorsed
    java.ext.dirs = /opt/jdk1.8.0_60/jre/lib/ext:/usr/java/packages/lib/ext
    java.home = /opt/jdk1.8.0_60/jre
    java.io.tmpdir = /tmp
    java.runtime.name = Java(TM) SE Runtime Environment
    java.runtime.version = 1.8.0_60-b27
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.version = 1.8.0_60
    java.vm.info = mixed mode
    java.vm.name = Java HotSpot(TM) 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Oracle Corporation
    java.vm.version = 25.60-b23
    line.separator = 

```
log4j.configurationFile = jar:file:/opt/incubator-geode/gemfire-assembly/build/install/apache-geode/lib/gemfire-core-1.0.0-incubating-SNAPSHOT.jar!/com/gemstone/gemfire/internal/logging/log4j/log4j2-default.xml
os.version = 3.10.0-327.3.1.el7.x86_64
p2p.useSSL = false
path.separator = :
spark.app.name = io.pivotal.demo.StockInferenceDemo
spark.driver.memory = 1G
spark.jars = file:/home/yy/StockInference-Spark/streaming/../lib/gemfire-spark-connector_2.10-0.5.0.jar,file:/opt/incubator-geode/gemfire-assembly/build/install/apache-geode/lib/gemfire-core-dependencies.jar,file:/home/yy/StockInference-Spark/streaming/../StockInference/build/libs/StockInference-1.0.jar
spark.master = local[*]
spark.submit.deployMode = client
sun.arch.data.model = 64
sun.boot.class.path = /opt/jdk1.8.0_60/jre/lib/resources.jar:/opt/jdk1.8.0_60/jre/lib/rt.jar:/opt/jdk1.8.0_60/jre/lib/sunrsasign.jar:/opt/jdk1.8.0_60/jre/lib/jsse.jar:/opt/jdk1.8.0_60/jre/lib/jce.jar:/opt/jdk1.8.0_60/jre/lib/charsets.jar:/opt/jdk1.8.0_60/jre/lib/jfr.jar:/opt/jdk1.8.0_60/jre/classes
sun.boot.library.path = /opt/jdk1.8.0_60/jre/lib/amd64
sun.cpu.endian = little
sun.cpu.isalist = 
sun.desktop = gnome
sun.io.unicode.encoding = UnicodeLittle
sun.java.command = org.apache.spark.deploy.SparkSubmit --master local[*] --conf spark.driver.memory=1G --class io.pivotal.demo.StockInferenceDemo --executor-memory 1G --jars ../lib/gemfire-spark-connector_2.10-0.5.0.jar,/opt/incubator-geode/gemfire-assembly/build/install/apache-geode//lib/gemfire-core-dependencies.jar ../StockInference/build/libs/StockInference-1.0.jar train
sun.java.launcher = SUN_STANDARD
sun.jnu.encoding = UTF-8
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
sun.nio.ch.bugLevel = 
sun.os.patch.level = unknown
user.country = US
user.language = en
user.timezone = Asia/Shanghai
```

---

[info 2015/12/29 14:25:56.419 CST <main> tid=0x1] Running in local mode since mcast-port was 0 and locators was empty.

[info 2015/12/29 14:25:58.429 CST <main> tid=0x1] Pool DEFAULT started with multiuser-authentication=false

[info 2015/12/29 14:25:58.444 CST <poolTimer-DEFAULT-3> tid=0x56] Updating membership port.  Port changed from 0 to 36,363.

15/12/29 14:25:59 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.io.NotSerializableException: com.gemstone.gemfire.cache.query.internal.StructImpl
Serialization stack:
    - object not serializable (class: com.gemstone.gemfire.cache.query.internal.StructImpl, value: struct(entryTimestamp:257320529324726,close:243.79,ema:243.777629543721,future_ema:243.77987871759,rsi:55.4265163313406,ema_diff:0.0123704562788305,low_diff:-1.78999999999999,high_diff:10.77))
    - element of array (index: 0)
    - array (class [Ljava.lang.Object;, size 1)
    at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
    at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
    at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:84)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:240)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
15/12/29 14:25:59 ERROR TaskSetManager: Task 0.0 in stage 0.0 (TID 0) had a not serializable result: com.gemstone.gemfire.cache.query.internal.StructImpl
Serialization stack:
    - object not serializable (class: com.gemstone.gemfire.cache.query.internal.StructImpl, value: struct(entryTimestamp:257320529324726,close:243.79,ema:243.777629543721,future_ema:243.77987871759,rsi:55.4265163313406,ema_diff:0.0123704562788305,low_diff:-1.78999999999999,high_diff:10.77))
    - element of array (index: 0)
    - array (class [Ljava.lang.Object;, size 1); not retrying
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0.0 in stage 0.0 (TID 0) had a not serializable result: com.gemstone.gemfire.cache.query.internal.StructImpl
Serialization stack:
    - object not serializable (class: com.gemstone.gemfire.cache.query.internal.StructImpl, value: struct(entryTimestamp:257320529324726,close:243.79,ema:243.777629543721,future_ema:243.77987871759,rsi:55.4265163313406,ema_diff:0.0123704562788305,low_diff:-1.78999999999999,high_diff:10.77))
    - element of array (index: 0)
    - array (class [Ljava.lang.Object;, size 1)
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1283)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1271)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1270)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1270)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:697)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:697)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1496)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1458)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1447)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
    at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:567)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1824)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1837)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1850)
    at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1302)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
    at org.apache.spark.rdd.RDD.take(RDD.scala:1276)
    at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1316)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
    at org.apache.spark.rdd.RDD.first(RDD.scala:1315)
    at io.pivotal.gemfire.spark.connector.internal.oql.SchemaBuilder.toSparkSchema(SchemaBuilder.scala:30)
    at io.pivotal.gemfire.spark.connector.internal.oql.OQLRelation.schema(RDDConverter.scala:13)
    at org.apache.spark.sql.execution.datasources.LogicalRelation.<init>(LogicalRelation.scala:37)
    at org.apache.spark.sql.SQLContext.baseRelationToDataFrame(SQLContext.scala:395)
    at io.pivotal.gemfire.spark.connector.GemFireSQLContextFunctions.gemfireOQL(GemFireSQLContextFunctions.scala:21)
    at io.pivotal.demo.StockInferenceDemo$.train(StockInferenceDemo.scala:66)
    at io.pivotal.demo.StockInferenceDemo$.main(StockInferenceDemo.scala:211)
    at io.pivotal.demo.StockInferenceDemo.main(StockInferenceDemo.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[info 2015/12/29 14:25:59.179 CST <Distributed system shutdown hook> tid=0x4a] VM is exiting - shutting down distributed system

[info 2015/12/29 14:25:59.180 CST <Distributed system shutdown hook> tid=0x4a] GemFireCache[id = 140778365; isClosing = true; isShutDownAll = false; created = Tue Dec 29 14:25:58 CST 2015; server = false; copyOnRead = false; lockLease = 120; lockTimeout = 60]: Now closing.

[info 2015/12/29 14:25:59.194 CST <Distributed system shutdown hook> tid=0x4a] Resetting original MemoryPoolMXBean heap threshold bytes 0 on pool PS Old Gen

[info 2015/12/29 14:25:59.212 CST <Distributed system shutdown hook> tid=0x4a] Destroying connection pool DEFAULT

**Comment by marcosantoniocaro** [comment]
(Is not the same case but someone else will fall in this issue by the subject),
If you got this Error:
`ERROR SparkContext: Jar not found at file:/lib/gemfire-core-dependencies.jar`

Just change in **train.sh** line 4 to this library **geode-dependencies.jar**
